# Generated by Django 3.2.7 on 2022-07-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='-', max_length=250)),
                ('uid', models.CharField(blank=True, max_length=250)),
                ('guests_number', models.PositiveIntegerField(blank=True, default=3)),
                ('rooms_number', models.PositiveIntegerField(blank=True, default=3)),
                ('start_date', models.DateField(blank=True, default='2020-10-10')),
                ('end_date', models.DateField(blank=True, default='2020-11-11')),
            ],
        ),
    ]
