# Generated by Django 3.2.7 on 2022-07-20 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('phone_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('request', models.CharField(max_length=5000)),
                ('credit_card_no', models.PositiveIntegerField()),
                ('expiry', models.PositiveBigIntegerField()),
                ('cvv', models.PositiveIntegerField()),
                ('billing_address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=250)),
                ('pax', models.PositiveIntegerField(blank=True)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='-', max_length=250)),
                ('uid', models.CharField(blank=True, max_length=250)),
                ('guests_number', models.PositiveIntegerField(blank=True, default=3)),
                ('rooms_number', models.PositiveIntegerField(blank=True, default=3)),
                ('start_date', models.DateField(blank=True, default='2020-10-10')),
                ('end_date', models.DateField(blank=True, default='2020-11-11')),
            ],
        ),
        migrations.CreateModel(
            name='HotelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelName', models.CharField(blank=True, default='Not Available', max_length=250)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='feat2')),
                ('cheapest_price', models.PositiveIntegerField(blank=True, default=0)),
                ('hotel_id', models.CharField(blank=True, default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='hotelNameToID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, max_length=250)),
                ('hotel_id', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='HotelPricesF2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(blank=True, max_length=250)),
                ('cheapest_price', models.DecimalField(blank=True, decimal_places=20, default=0, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='KLHotelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, max_length=250)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='kl')),
                ('rating', models.PositiveIntegerField(blank=True)),
                ('price', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SingaporeHotelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, max_length=250)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='singapore')),
                ('rating', models.PositiveIntegerField(blank=True)),
                ('price', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
