# Generated by Django 3.2.7 on 2022-07-20 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DestinationSearch',
        ),
    ]
