# Generated by Django 3.2.7 on 2022-08-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreviousBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_key', models.CharField(blank=True, default='-', max_length=250)),
                ('room_type', models.CharField(blank=True, default='-', max_length=250)),
                ('hotel_name', models.CharField(blank=True, default='-', max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel_id',
            field=models.CharField(default='-', max_length=1000),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.CharField(default='-', max_length=1000),
        ),
    ]
