# Generated by Django 3.2.7 on 2022-07-26 09:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0002_booking_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature3_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('hotel_name', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('hotel_address', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('latitude', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('longitude', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('rating', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('amenities_ratings', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('description', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('trustyou_score_overall', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('trustyou_score_solo', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('trustyou_score_couple', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('trustyou_score_family', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('trustyou_score_business', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('image_details_suffix', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('default_image_index', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('cloudflare_image_url', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('image_url_ForUse', models.CharField(blank=True, default='None', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelName', models.CharField(blank=True, default='Not Available', max_length=250)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='feat2')),
                ('cheapest_price', models.PositiveIntegerField(blank=True, default=0)),
                ('hotel_id', models.CharField(blank=True, default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='hotelNameToID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, max_length=250)),
                ('hotel_id', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='HotelPricesF2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(blank=True, max_length=250)),
                ('cheapest_price', models.DecimalField(blank=True, decimal_places=20, default=0, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoomsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_key', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('roomDescription', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('roomNormalizedDescription', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('free_cancellation', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('roomAdditionalInfo', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('surcharges', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('long_description', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('images_URLs', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('amenities', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('price_type', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('max_cash_payment', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('coverted_max_cash_payment', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('points', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('bonuses', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('lowest_price', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('price', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('converted_price', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('lowest_converted_price', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('chargeableRate', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('market_rates', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('imageURL_forUse', models.CharField(blank=True, default='None', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KLHotelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, max_length=250)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='kl')),
                ('rating', models.PositiveIntegerField(blank=True)),
                ('price', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SingaporeHotelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, max_length=250)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='singapore')),
                ('rating', models.PositiveIntegerField(blank=True)),
                ('price', models.PositiveIntegerField(blank=True)),
            ],
        ),
    ]
