# Generated by Django 4.0.5 on 2022-07-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0002_delete_destinationsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature3_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(blank=True, max_length=250)),
                ('latitude', models.DecimalField(blank=True, decimal_places=3, max_digits=7)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, max_digits=7)),
                ('rating', models.PositiveIntegerField(blank=True)),
                ('amenities_ratings', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('trustyou_score_overall', models.PositiveIntegerField(blank=True)),
                ('trustyou_score_solo', models.PositiveIntegerField(blank=True)),
                ('trustyou_score_couple', models.PositiveIntegerField(blank=True)),
                ('trustyou_score_family', models.PositiveIntegerField(blank=True)),
                ('trustyou_score_business', models.PositiveIntegerField(blank=True)),
                ('image_details_suffix', models.CharField(blank=True, max_length=250)),
                ('default_image_index', models.CharField(blank=True, max_length=250)),
                ('cloudflare_image_url', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
