# Generated by Django 4.0.5 on 2022-07-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0003_feature3_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature3_info',
            name='hotel_address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='feature3_info',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
