# Generated by Django 3.2.7 on 2022-07-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0003_feature3_info_hotellist_hotelnametoid_hotelpricesf2_hotelroomsinfo_klhotellist_singaporehotellist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
