# Generated by Django 4.0.5 on 2022-07-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0004_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPicturesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.CharField(blank=True, default='None', max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotellist',
            name='image',
        ),
        migrations.AddField(
            model_name='feature3_info',
            name='amenities',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='feature3_info',
            name='imageIndices',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='hotellist',
            name='imageURL',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
    ]
