# Generated by Django 3.2.7 on 2022-08-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0005_hotelpicturesmodel_remove_hotellist_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bank',
            field=models.CharField(choices=[('DBS', 'DBS'), ('OCBC', 'OCBC'), ('HSBC', 'HSBC'), ('Credit Suisse', 'Credit Suisse'), ('American Express', 'American Express')], default='green', max_length=20),
        ),
        migrations.AlterField(
            model_name='feature1',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature1',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
