# Generated by Django 3.2.7 on 2022-08-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0006_auto_20220801_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_key',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
