# Generated by Django 4.0.5 on 2022-07-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0006_alter_feature3_info_amenities_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature3_info',
            name='amenities_ratings',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='feature3_info',
            name='cloudflare_image_url',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='feature3_info',
            name='default_image_index',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='feature3_info',
            name='description',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='feature3_info',
            name='hotel_address',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='feature3_info',
            name='hotel_id',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='feature3_info',
            name='hotel_name',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='feature3_info',
            name='image_details_suffix',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='feature3_info',
            name='latitude',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='feature3_info',
            name='longitude',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='feature3_info',
            name='rating',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='feature3_info',
            name='trustyou_score_business',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='feature3_info',
            name='trustyou_score_couple',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='feature3_info',
            name='trustyou_score_family',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='feature3_info',
            name='trustyou_score_overall',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='feature3_info',
            name='trustyou_score_solo',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
    ]
