# Generated by Django 4.0.5 on 2022-07-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0007_alter_feature3_info_amenities_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature3_info',
            name='image_url_ForUse',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
    ]
