# Generated by Django 4.0.5 on 2022-07-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0008_feature3_info_image_url_foruse'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoomsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_key', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('roomDescription', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('roomNormalizedDescription', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('free_cancellation', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('roomAdditionalInfo', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('surcharges', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('long_description', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('images_URLs', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('amenities', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('price_type', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('max_cash_payment', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('coverted_max_cash_payment', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('points', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('bonuses', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('lowest_price', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('price', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('converted_price', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('lowest_converted_price', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('chargeableRate', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('market_rates', models.CharField(blank=True, default='None', max_length=250, null=True)),
            ],
        ),
    ]
