# Generated by Django 3.2.7 on 2022-08-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0008_alter_booking_credit_card_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_key',
        ),
    ]
