# Generated by Django 3.2.7 on 2022-08-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0009_remove_booking_booking_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_key',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='credit_card_no',
            field=models.PositiveIntegerField(),
        ),
    ]
