# Generated by Django 4.0.5 on 2022-07-21 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0009_hotelroomsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroomsinfo',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
