# Generated by Django 3.2.7 on 2022-08-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0010_auto_20220802_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='credit_card_no',
            field=models.CharField(max_length=16),
        ),
    ]
