# Generated by Django 4.0.5 on 2022-07-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0010_hotelroomsinfo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroomsinfo',
            name='imageURL_forUse',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
    ]
