# Generated by Django 3.2.7 on 2022-08-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0011_alter_booking_credit_card_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='booking',
            name='expiry',
            field=models.CharField(max_length=4),
        ),
    ]
