# Generated by Django 3.2.7 on 2022-08-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0012_auto_20220803_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature1HotelSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, default='-', max_length=250)),
                ('hotel_id', models.CharField(blank=True, default='-', max_length=250)),
                ('dest_id', models.CharField(blank=True, default='-', max_length=250)),
                ('guests_number', models.PositiveIntegerField(blank=True, default=3)),
                ('rooms_number', models.PositiveIntegerField(blank=True, default=3)),
                ('start_date', models.DateField(blank=True, default='2020-10-10')),
                ('end_date', models.DateField(blank=True, default='2020-11-11')),
            ],
        ),
    ]
